src/main/java/org/popcraft/chunky/command/StartCommand.java
src/main/resources/lang/bg.json
src/main/resources/lang/de.json
src/main/resources/lang/en.json
src/main/resources/lang/es.json
src/main/resources/lang/fr.json
src/main/resources/lang/pt.json
src/main/resources/lang/ru.json
src/main/resources/lang/tr.json
src/main/resources/lang/zh_CN.json

Fixes an issue where when using two radii, starting a task would confusingly not show the second radius.

Show radius in start message properly

---

src/main/java/org/popcraft/chunky/command/CancelCommand.java
src/main/resources/lang/en.json

This changes the cancel command to properly inform the user if any tasks were actually cancelled, rather than just always saying that all tasks were cancelled.
Hopefully good enough, let me know if you want to see any changes <3

Provide a better message if trying to cancel with no tasks

---

src/main/java/org/popcraft/chunky/command/PauseCommand.java
src/main/resources/lang/en.json

This changes the pause command to properly inform the user if there were no tasks to pause, rather than returning nothing and leaving the user with no command feedback whatsoever.
Hopefully good enough, let me know if you want to see any changes <3

Provide a better message if trying to pause with no tasks

---

src/main/java/org/popcraft/chunky/Chunky.java
src/main/java/org/popcraft/chunky/ConfigStorage.java
src/main/java/org/popcraft/chunky/GenerationTask.java
src/main/java/org/popcraft/chunky/command/CancelCommand.java
src/main/java/org/popcraft/chunky/command/PauseCommand.java

If shutting down, save tasks sync. This should fix issues that people are having with tasks not saving properly or the async task taking too long to shut down.

Improve shutdown by saving tasks sync

---

src/main/java/org/popcraft/chunky/command/ContinueCommand.java
src/main/resources/lang/en.json

This changes the continue command to properly inform the user if there were no tasks to continue, rather than returning nothing and leaving the user with no command feedback whatsoever.
This is the last PR I'll be doing that involve these command feedback stuff :P This was the last command that provided no feedback in Chunky. They now all give some sort of feedback always :)
Hopefully good enough, let me know if you want to see any changes <3

Provide a better message if trying to continue with no tasks

---

forge/build.gradle.kts
forge/src/main/java/org/popcraft/chunky/ChunkyForge.java
forge/src/main/java/org/popcraft/chunky/command/suggestion/PatternSuggestionProvider.java
forge/src/main/java/org/popcraft/chunky/command/suggestion/ShapeSuggestionProvider.java
forge/src/main/java/org/popcraft/chunky/command/suggestion/SuggestionProviders.java
forge/src/main/java/org/popcraft/chunky/platform/ForgeBorder.java
forge/src/main/java/org/popcraft/chunky/platform/ForgeSender.java
forge/src/main/java/org/popcraft/chunky/platform/ForgeServer.java
forge/src/main/java/org/popcraft/chunky/platform/ForgeWorld.java

This PR addresses the [discontinuation of MCP mappings](https://mcforge.readthedocs.io/en/latest/gettingstarted/#migration-to-mojangs-official-mappings) by migrating to the official Mojang mappings, which is the recommended migration path.
This is an important step towards 1.17.
Reminder that the mappings come with the following license:
`(c) 2020 Microsoft Corporation. These mappings are provided "as-is" and you bear the risk of using them. You may copy and use the mappings for development purposes, but you may not redistribute the mappings complete and unmodified. Microsoft makes no warranties, express or implied, with respect to the mappings provided here.  Use and modification of this document or the source code (in any form) of Minecraft: Java Edition is governed by the Minecraft End …

[Forge] Migrate from MCP to Mojang Mappings

---

fabric/build.gradle.kts

This PR addresses the Gradle deprecation warnings during normal build as well as the massive spam during loom operations by updating to Loom 0.9 - which has been promoted to stable as of today.

[Fabric] Update Loom to 0.9

---

forge/build.gradle.kts
forge/src/main/java/org/popcraft/chunky/ChunkyForge.java
forge/src/main/java/org/popcraft/chunky/listeners/BossBarProgress.java
forge/src/main/java/org/popcraft/chunky/platform/ForgeWorld.java
forge/src/main/resources/META-INF/accesstransformer.cfg

This PR addresses the fact that multiple features / bug fixes have happened for Fabric that do not exist for Forge due to the period of time in which Forge was not being built.
I have done a complete diff between the two modules and have ported any fixes / features. I've also bumped the FML version to target the latest recommended build for 1.16.5.
Notable features include progress command, boss bars for client users, very fast chunk generated method, etc
Some interesting workarounds had to be done in some cases when porting, due to FML issues.
The getting of a chunk status had to be changed as FML lists the internal method as being client only - which is definitely not true, so a workaround had to be made via helper method.
The text component stuff in the boss bars was having an …

[Forge] Improve parity with Fabric

---

fabric/src/main/java/org/popcraft/chunky/platform/FabricSender.java
fabric/src/main/java/org/popcraft/chunky/platform/FabricServer.java

This PR simplifies some of the Fabric logic to align better with the Forge module.
This does come with a behavior change - instead of a `Console` sender being hardcoded to `x: 0, z: 0`, it will now actually return the position that the server provides (which is world spawn position, unless otherwise changed via `execute` command). 
This is the same behavior as Forge and is the most **correct** behavior compared to the other modules.

[Fabric] Simplify world and sender logic

---

fabric/src/main/java/org/popcraft/chunky/platform/FabricWorld.java
forge/src/main/java/org/popcraft/chunky/platform/ForgeWorld.java

This PR aims to make the chunk scheduling method use a potentially better alternative after looking through the server code.
(I will be using Mojang mapped class / method names for this analysis)
Currently, a chunk is scheduled to be brought to `FULL` status by using `ChunkMap#schedule(holder, status)`.
Upon looking through the server code, the only time `ChunkMap#schedule(holder, status)` is ever used internally is by `ChunkHolder#getOrScheduleFuture(status, chunkMap)`.
`ChunkHolder#getOrScheduleFuture(status, chunkMap)` is used much more commonly internally, and since it's still a caller of `ChunkMap#schedule(holder, status)` with a few extra checks, I believe it's better for us to use this purely for using the chunk system responsibly and in a way that coincides with the vanilla code. …

[Fabric/Forge] Use alternative chunk scheduling method

---

common/src/main/java/org/popcraft/chunky/platform/impl/SimpleScheduler.java

This PR addresses an undesirable behavior of SimpleScheduler.
The intended behavior of SimpleScheduler is to queue up tasks and execute them unbounded, with 3 threads ready to go upon startup that expire after 5 minutes if nothing happens. There should be an unlimited amount of tasks able to execute at the same time, given that the user wants to pregenerate a ton of worlds. We do not want to limit what users choose to do. We choose 3 as the initial thread count as there are three worlds in vanilla.
SimpleScheduler has three issues that differed from this intended functionality:
- The core threads were never being initialized on startup, so the whole "3 threads ready to go" wasn't actually happening until a task was first started.
- The core threads were never being allowed to expire, …

[Common] Fix SimpleScheduler behavior

---

sponge/src/main/java/org/popcraft/chunky/ChunkySponge.java

This PR implements the `continue-on-restart` feature that all other platform modules have.
It properly waits until the server has loaded to execute, so should be compatible with any multi world mods/plugins similar to Bukkit.

[Sponge] Implement "continue-on-restart" feature

---

sponge/src/main/java/org/popcraft/chunky/platform/SpongeConfig.java
sponge/src/main/resources/main.conf

This PR addresses a few configuration issues that exist with the Sponge module
- The `tasks` node was being placed inside of the `config` node instead of being its own root node
- `version`, `language` and `continue-on-restart` were told to be root nodes in the code, but were being shipped in the default configuration file as inside of the `config` node, leading to duplicate entries and only the ones at the root actually working
- The shipped default configuration file uses perfectly valid HOCON, but isn't the same style of HOCON that Configurate (and Sponge) use by default. It gets converted automatically on the users end.
- The shipped default configuration file isn't alphabetically sorted, so it will automatically get sorted when loaded on the server. Not really an issue, but it's best …

[Sponge] Fix various configuration issues

---

forge/build.gradle.kts
forge/src/main/java/org/popcraft/chunky/ChunkyForge.java
forge/src/main/java/org/popcraft/chunky/platform/ForgeWorld.java
forge/src/main/resources/META-INF/mods.toml
forge/src/main/resources/pack.mcmeta

This PR updates the Forge module to 1.18.
Not many changes were needed. I've ported all of the Fabric 1.18 fixes / changes.
Arch Loom was just updated a few hours ago for Forge 1.18 support, so it's still fresh and there appears to be a nasty looking stacktrace when building. It doesn't fail the build and the jar produced seems perfectly fine, so it's "safe" to ignore for now. It will likely resolve itself in future builds as we're building against an ever changing snapshot version.
I've tested all typical functionally of Chunky and all seems to work fine. (pregen, trim, world changing, boss bar in game, etc)

[Forge] Update to 1.18

---

build.gradle.kts
bukkit/build.gradle.kts
bukkit/src/main/resources/plugin.yml
common/build.gradle.kts
common/src/main/java/org/popcraft/chunky/integration/SquaremapIntegration.java

This PR adds [Squaremap](https://github.com/jpenilla/squaremap) integration, which fully replaces the Pl3xMap integration. It also allows Chunky to compile again...
Pl3xMap has been archived and is no longer supported in any official capacity, and adding insult to injury, the pl3x maven repository is now giving a permanent `503` which prevents Chunky from continuing to support Pl3xMap, let alone compile... this effectively forces our hand in making a decision now rather than later, and it's clear Squaremap is the proper continuation of Pl3xMap.
This is a breaking change for anyone who still uses Pl3xMap - those users will either need to continue to use an old version of Chunky + ChunkyBorder or they will need to migrate to Squaremap. We should recommend the usage of Squaremap as a …

Add Squaremap Integration

---

fabric/src/main/java/org/popcraft/chunky/mixin/ServerChunkManagerMixin.java
fabric/src/main/java/org/popcraft/chunky/mixin/ThreadedAnvilChunkStorageMixin.java
fabric/src/main/java/org/popcraft/chunky/platform/FabricWorld.java

When using Chunky in mapped Fabric devlaunch, the implementation of mixin accessor interfaces into Vanilla classes causes recursive invocation due to matching method names, which then causes a stack overflow. This pull request prepends `invoke` to the invoker methods to prevent name conflicts in mapped environments, per standard.
Stack trace: 
```
java.lang.StackOverflowError: Exception initializing level
at net.minecraft.server.world.ThreadedAnvilChunkStorage.getChunkHolder(ThreadedAnvilChunkStorage.java)
at net.minecraft.server.world.ThreadedAnvilChunkStorage.getChunkHolder(ThreadedAnvilChunkStorage.java)
at net.minecraft.server.world.ThreadedAnvilChunkStorage.getChunkHolder(ThreadedAnvilChunkStorage.java)
at net.minecraft.server.world.ThreadedAnvilChunkStorage.getChunkHolder(ThreadedAnv …
```

Fix Fabric devlaunch

---

bukkit/src/main/java/org/popcraft/chunky/platform/BukkitPlayer.java

Based on this plugin that does it: https://github.com/TheMrJezza/HorseTpWithMe/blob/master/src/main/java/com/jbouchier/horsetpwithme/util/BlinkTeleportUtil.java
It mostly works, minecarts and pigs on a saddle and horses. Boats for some reason get teleported, however only a client reload shows the boat present.
I have never coded for a Bukkit plugin before so any and all changes/constructive criticism are welcome. Thank you :)

Tweak Bukkit teleporting vehicles logic

---

fabric/src/main/java/org/popcraft/chunky/platform/FabricWorld.java

This PR removes the waiting behavior of `getChunkAtAsync` and `isChunkGenerated`, bringing parity with Paper and potentially better throughput on Fabric platform.

perf: do not wait for server thread when dispatching tasks

---

bukkit/src/main/java/org/popcraft/chunky/platform/BukkitPlayer.java
folia/src/main/java/org/popcraft/chunky/platform/Folia.java
paper/src/main/java/org/popcraft/chunky/platform/Paper.java

Fixes teleporting players with vehicles on folia since I encountered some issues with this in chunkyborder. The teleport flag api is used for same world teleports and the rest of the method is modified to make sure we're on the region thread for the player.

Fix vehicle teleports on folia

---

bukkit/src/main/java/org/popcraft/chunky/platform/BukkitWorld.java

When World#getElevation is called from a region thread for a location that's owned by that same region, it causes the region to get "stuck" since the completablefuture can never finish.
(For reproduction, I used getElevation with the player's x and z coords inside onCommand)

Fix folia region getting stuck when World#getElevation is used

---

fabric/build.gradle.kts
fabric/src/main/java/org/popcraft/chunky/mixin/MinecraftServerMixin.java
fabric/src/main/java/org/popcraft/chunky/platform/FabricPlayer.java
fabric/src/main/java/org/popcraft/chunky/platform/FabricWorld.java
fabric/src/main/resources/chunky.mixins.json
fabric/src/main/resources/fabric.mod.json
forge/build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
neoforge/build.gradle.kts

Dedicated server now pauses automatically since 24w33a. Pausing causes trouble for the vanilla chunk system, and therefore this PR unpauses the server while it is doing generation tasks.

Port fabric to 1.21.3 and prevent pausing during pregen tasks

---

common/src/main/java/org/popcraft/chunky/iterator/WorldChunkIterator.java

… if the `force-load-existing-chunks` option is used.

Make WorldChunkIterator also process chunks that are not fully generated

---

bukkit/src/main/java/org/popcraft/chunky/platform/BukkitWorld.java

This properly resolves rare conditions with getElevation which cause regions to effectively implode. Although this is a rare race condition, it is very much real and should be dealt with promptly. The previously applied fix did not adequately resolve this, since blocking with `.join` on Folia is simply not a good strategy.

Properly resolve rare Folia region blockages when retrieving getElevation, using managedBlock, using managedBlock
